version: "3"

services:
    web:
        hostname: web
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --log-level debug --reload
        volumes:
          - ./app:/app
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db
    db:
        hostname: ${POSTGRES_HOSTNAME}
        image: postgres:15
        container_name: database
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        env_file:
            - .env